services:
    gestione:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: gestione
        restart: unless-stopped
        networks:
            - network_liberica
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.gestione.rule=Host(`gestione.liberica.pt`)"
            - "traefik.http.routers.gestione.entrypoints=websecure"
            - "traefik.http.routers.gestione.tls.certresolver=letsencrypt"
            - "traefik.http.services.gestione.loadbalancer.server.port=80"

networks:
    network_liberica:
        external: true
